### ISSUE TITLE
beginner to pyqt

### ISSUE THREAD

**Issue by rickyi22** [maicss/PyQt-Chinese-tutorial#1]
我最近刚刚接触PyQt， 想做一个简单的工具。 在用户上输入一个数据后，查询本地计算机上此数据的相关信息，然后输出一个相关信息汇总的表格，找了很多教程都没找到，我现在的代码是
`
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import QCoreApplication

class Qtone(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        QToolTip.setFont(QFont('SansSerif', 10))

        btn = QPushButton('account_id', self)
        btn.clicked.connect(self.showDialog)
        btn.resize(btn.sizeHint())
        btn.move(100, 100)

        layout = QHBoxLayout()
        layout.addWidget(self.Mytable)
        self.setGeometry(1000, 500, 1000, 500)

        self.show()

    def tableview(self):
        self.Mytable = QTableWidget(5, 5)
        self.Mytable.setHorizontalHeaderLabels(['time', 'id', 'column1', 'column2'])

        newItem = QTableWidgetItem('20170830')
        self.MyTable.setItem(0, 0, newItem)

        newItem = QTableWidgetItem('rickyi22')
        self.MyTable.setItem(0, 1, newItem)

        newItem = QTableWidgetItem('info1')
        self.MyTable.setItem(0, 2, newItem)

        newItem = QTableWidgetItem('info2')
        self.MyTable.setItem(0, 3, newItem)

        layout = QHBoxLayout()
        layout.addWidget(self.Mytable)
        self.setLayout(layout)

    def showDialog(self):

        text, ok = QInputDialog.getText(self, 'Input Dialog',
                                        'Enter your name:')
        if ok:
            # 数据操作 收集数据
            self.tableview()

    def closeEvent(self, event):
        reply = QMessageBox.question(self, 'Message', 'blue or red?', QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

if __name__ == "__main__":
    app = QApplication(sys.argv)

    ex = Qtone()
    sys.exit(app.exec_())
`
我想的是点击之后 接收数据后输出一个表格 但是运行会直接python挂掉，请问是哪里出了什么问题吗？

**Comment by maicss** [comment]
呃，你把我这当入门课堂了么，具体什么类型的问题你也不知道，直接让人帮你debug代码啊……

**Comment by maicss** [comment]
我只说几个语法问题，其他的你还是自己看API吧。

1. 最后的运行，是`__name__`，不是`name`。我不知道你说的挂掉是不是这个，这个会导致挂掉的。你给别人描述你的需求和问题的时候，自己不知道挂掉的原因最起码也得贴出来你的错误堆栈吧……让别人猜你的问题可能是什么？而且你还没说你的Python版本。
2. markdown贴代码，有换行的时候，是三个反引号，不是一个。你自己贴了代码之后点提交，不是有预览吗？这么难看也不修改直接提交？
3. 代码里面：`newItem = QTableWidgetItem('20170830')`，你知道数据类型有值类型和引用类型吗？你就这样一直使用这一个变量，以为是赋值了新的值，然后使用，然后再赋值。这样不会出错吗（我不确定是不是这里的问题）？你自己不会debug，总会`print`吧，没事打印出来看看是不是你想要的啊。
4. 你问如果还要问其他人的话，建议你把你的数据伪造一份，直接在代码里面用一个变量写好，然后用Qt渲染这份伪造的数据就好了。不然别人连你的数据结构是什么也不知道。

就这吧。

**Comment by rickyi22** [comment]
嗯嗯  不好意思，因为看到在翻译教程 所以问问。 我需求大概已经完成了，就是我想的是一个文本框，获得输入的数据，然后读取本地的一个txt文档，然后显示与输入数据相关的信息。

**Comment by rickyi22** [comment]
嗯嗯 不好意思，因为看到在翻译教程 所以问问。谢谢了
