### ISSUE TITLE
链接无法访问

### ISSUE THREAD

**Issue by Masterchiefm** [maicss/PyQt-Chinese-tutorial#15]
链接无法访问，直接就转跳gitbook官网主页了

**Comment by aoout** [comment]
我也是

**Comment by aoout** [comment]
> 链接无法访问，直接就转跳gitbook官网主页了

https://maicss.gitbooks.io/pyqt5/content/

**Comment by maicss** [comment]
gitbook更新导致的，已修复。

**Comment by aoout** [comment]
> gitbook更新导致的，已修复。

我点了之后还是会到主页去
