### ISSUE TITLE
右侧链接有误

### ISSUE THREAD

**Issue by aoout** [maicss/PyQt-Chinese-tutorial#16]
![image](https://user-images.githubusercontent.com/60838705/107586499-ff2d6480-6c3a-11eb-9c5e-3570232c8d8f.png)

和下面的链接不符。而且前者只会被跳转到主页去。

![image](https://user-images.githubusercontent.com/60838705/107586527-10767100-6c3b-11eb-864a-574195252615.png)

**Comment by maicss** [comment]
已更新
