### ISSUE TITLE
PyQt6教程问题

### ISSUE THREAD

**Issue by Candysad** [maicss/PyQt-Chinese-tutorial#23]
translated/pyqt6/firstprograms.md

`PyQt6 弹窗` 一节的代码文件 `messagebox.py` 中第34行QMessageBox.question函数的参数 `QMessageBox.StandardButtons` 的调用均应该是 `QMessageBox.StandardButton`
已对照英文原版检查，可能是更新导致的修改？

另外此处和英文原版这一小节对QMessageBox.question函数的解释使用的应该都是pyqt5的代码，不知道是为什么

```
reply = QMessageBox.question(self, 'Message',
                             "Are you sure to quit?", QMessageBox.Yes |
                             QMessageBox.No, QMessageBox.No)
```

**Comment by oracle5** [comment]
邮件已经收到，谢谢。

**Comment by Candysad** [comment]
`PyQt6 的菜单和工具栏` 一节 `PyQt6 子菜单` 处的实例代码开头未将文件名 `submenu.py` 放入注释而是直接写在代码里了

**Comment by maicss** [comment]
谢谢反馈，已解决。
