### ISSUE TITLE
py

### ISSUE THREAD

**Issue by xipeng5** [maicss/PyQt-Chinese-tutorial#26]

**Comment by oracle5** [comment]
邮件已经收到，谢谢。

**Comment by xipeng5** [comment]
py6和py5的弹窗两种感觉不一样。博主的博客没显示两种方式的区别。用py6调py5不行的。

**Comment by maicss** [comment]
1，感觉不一样是不是正常的？
2，本来就是两个版本的教程，不是两个版本的对比，不显示区别也没什么吧。
3，py6为啥要带py5的代码呢？
