### ISSUE TITLE
readme的链接给错了

### ISSUE THREAD

**Issue by KJH-x** [maicss/PyQt-Chinese-tutorial#27]
问题在readme.md 的第6行和第8行

开始阅读 \[PyQt5\]\(https://github.com/maicss/PyQt-Chinese-tutorial/blob/master/pyqt5/index.md \) 教程。

开始阅读 \[PyQt6\]\(https://github.com/maicss/PyQt-Chinese-tutorial/blob/master/pyqt6/index.md \) 教程。

此处应为 https://maicss.gitbook.io/pyqt-chinese-tutoral/pyqt6
以及 https://maicss.gitbook.io/pyqt-chinese-tutoral/pyqt5

**Comment by oracle5** [comment]
邮件已经收到，谢谢。
