### ISSUE TITLE
https://maicss.gitbooks.io/pyqt5/content/可能无法正确获取页面

### ISSUE THREAD

**Issue by Liyulingyue** [maicss/PyQt-Chinese-tutorial#28]
仅能展示介绍页面，后面的布局管理等内容无法正确刷新出来。

**Comment by oracle5** [comment]
邮件已经收到，谢谢。

**Comment by maicss** [comment]
哥们，你咋老是自动回复这个repo的issue？😂

发自iPhone 18

**Comment by Liyulingyue** [comment]
> 哥们，你咋老是自动回复这个repo的issue？😂 发自iPhone 18
> […](#)
> 在 2022年9月12日，13:04，oracle5 ***@***.***> 写道： ﻿ 邮件已经收到，谢谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

失敬失敬，我还以为maicss是一个公共服务网站哈哈哈哈

**Comment by maicss** [comment]
不是说的你🤣

发自iPhone 18

**Comment by maicss** [comment]
这个链接早就废弃了吧，你在哪里找到这个链接的？

**Comment by Liyulingyue** [comment]
> 这个链接早就废弃了吧，你在哪里找到这个链接的？

应该是bing或者baidu搜索'pyqt5 中文教程'找到的

**Comment by madahademeng** [comment]
图片怎么显示不出来，需要梯子吗

**Comment by maicss** [comment]
gitbooks.io的缓存我不知道怎么关闭。没办法了，只能这样了。这个issue就关闭了
