### ISSUE TITLE
病句？

### ISSUE THREAD

**Issue by hzy3000** [maicss/PyQt-Chinese-tutorial#4]
事件和信号中 “事件是这个对象状态的改变撞他改变的内容” 这句有问题。
是不是“事件是这个对象状态改变的内容” 。

**Comment by maicss** [comment]
嗯，mac打字总是有点意外发生。https://github.com/maicss/PyQt5-Chinese-tutoral/commit/ed7cae578d4aafb3e488793c52a569751e6ed055
