### ISSUE TITLE
pyqt5无法复现子menu的操作

### ISSUE THREAD

**Issue by frankcreating** [maicss/PyQt-Chinese-tutorial#5]
pyqt5无法复现子menu的操作。感觉网上清一色的blog都是渣渣，现在实现不了这个功能浑身难受。。

**Comment by maicss** [comment]
...所以我可以怎么帮你？

**Comment by onebits** [comment]
所以为什么抄到我这里一份了???
我关注了问题还是怎么样了?我做了什么?

**Comment by frankcreating** [comment]
不好意思，我不知道这个issue发送面积会有这么广。。我再想办法解决，有结果的话我会贴上来

**Comment by maicss** [comment]
所以你只是抱怨一下？这有点逗了吧...

**Comment by onebits** [comment]
@maicss  该忙啥忙啥啊...玩会游戏也好啊..

**Comment by frankcreating** [comment]
emmm只是抱怨我不会发这里的

**Comment by maicss** [comment]
所以你在说什么，是这个教程哪里不对了？还是你想让我帮你做个功能？

**Comment by maicss** [comment]
> @maicss 该忙啥忙啥啊...玩会游戏也好啊..
虽然我也不知道这个issue为啥提到了你，但是你可以点击右边点unsubscribe取消订阅

**Comment by coding-today** [comment]
https://maicss.gitbook.io/pyqt-chinese-tutoral/pyqt5/cai-dan-he-gong-ju-lan#cai-dan-lan   菜单功能按照一模一样的代码，无法显示菜单。希望修复一下

**Comment by oracle5** [comment]
邮件已经收到，谢谢。

**Comment by coding-today** [comment]
解决了 是操作系统问题，
Macos 系统需要增加  `menubar.setNativeMenuBar(False)` 到 menubar初始化之后
